### ISSUE TITLE
Serial Read Data

### ISSUE THREAD

**Issue by SauloAislan** [AprilBrother/android-blueduino#1]
I am in need to read data from the serial port Blueduino, but I can not, I'm using https://github.com/AprilBrother/android-blueduino/tree/master/Example/Blueduino/src/com/aprilbrother/blueduino, but nothing happens after I click the ZeroBeacon appears a screen loading please wait, and not out of it. 
I am using this code in blueduino: https://github.com/volca/BlueDuino/blob/master/examples/serial_test.ino

@volca Please help me.

**Comment by volca** [comment]
Please see [the post](http://bbs.aprbrother.com/t/read-temperature-sensor-to-serial-blueduino/528)
